run:
  build-tags:
    - test
    - integration
linters:
  enable:
    - gofmt
    - misspell
    - godot
    - whitespace
    - gci
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/canonical/microcloud/microcloud)
